name: Test

on:
  push:
    branches:
    - main

env:
  REGISTRY: ghcr.io

jobs:
  test:
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    runs-on: ubuntu-latest
    services:
      dovecot:
        image: ghcr.io/marzocchi/dovecot-test:latest
        ports:
          - "10143:143"
          - "10993:993"

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24
          elixir-version: 1.13.3

      - name: Get deps
        run: mix deps.get
      - name: Run tests
        run: mix test

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/marzocchi/imapfilter:latest
